//
// Created by admin on 2021/12/03.
//

#ifndef COMP_PROGRAMMINGS_ATWONUMBERPROBLEM_H
#define COMP_PROGRAMMINGS_ATWONUMBERPROBLEM_H


int twoNumberProblem();


#endif //COMP_PROGRAMMINGS_ATWONUMBERPROBLEM_H
